### ISSUE TITLE
Test integration w/ 2 separate react native components

### ISSUE THREAD

**Issue by inakianduaga** [inakianduaga/react-native-demo#2]

**Comment by inakianduaga** [comment]
# TODO:

- [ ] Pass initial navigation position from native core to the application and use that as initial app navigation state if available
- [ ] Update RN application bootstrap to read this value (or default to home if not provided) 
- [ ] Add another activity on Android that will be the detail's page
- [ ] Toggle to this activity when we switch paths
- [ ] We might need to fetch movie details by listening to `@INIT` action and checking the state at that point in time, if it's details page we need to fetch info.

**Comment by inakianduaga** [comment]
Secondary activity tutorial

https://developer.android.com/training/basics/firstapp/starting-activity.html
